name: NodeJS CI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Create env file
        run: |
          touch .env
          echo SSH_HOST=164.90.172.241 >> .env
          echo SSH_USER=root >> .env
          echo GIT_REPOSITORY=git@github.com:rherwig/watch.git >> .env
          echo GIT_BRANCH=origin/main >> .env
          echo WEB_ROOT=/var/www/watch >> .env

      - name: Install PM2
        run: npm i pm2

      - name: Status
        run: git status

      - name: Deploy
        run: env $(cat .env | grep -v \"#\" | xargs) npm run deploy
